PWWServ_Client/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace PWWServ_Client.Models
{
    public class Customer
    {
        [Display(Name="E-Mail")]
        public string Email { get; set; }
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        [Display(Name = "Second Name")]
        public string SecondName { get; set; }
        [Display(Name = "Password")]
        public string PassHesh { get; set; }
    }
}

PWWServ_Client/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using PWWServ_Client.Models;
using PWWServ_Client.ViewModels;

namespace PWWServ_Client.Controllers
{
    public class CustomerController : Controller
    {
        public ActionResult Index()
        {
            PWServiceClient pwc = new PWServiceClient();
            ViewBag.ListCustomers = pwc.All();
            return View();
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View("Create");
        }

        [HttpPost]
        public ActionResult Create(CustomerVM inCVM)
        {
            PWServiceClient pwc = new PWServiceClient();
            pwc.CreateCustomer(inCVM.Customer);
            return RedirectToAction("Index");
        }

        
        public ActionResult Delete(string inEmail)
        {
            PWServiceClient pwc = new PWServiceClient();
            pwc.Delete(pwc.Find(inEmail));
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View("Login");
        }

        [HttpPost]
        public ActionResult Login(CustomerVM inCVM)
        {
            PWServiceClient pwc = new PWServiceClient();
            Customer _cust = pwc.Login(inCVM.Customer.Email, inCVM.Customer.PassHesh);
            if (_cust == null)
                return View("ErrorLogin");
            else
            {
                List<Transfer> _rts = pwc.FindCustTransfers(_cust.Email);
                ViewBag.Customer = _cust;
                ViewBag.Transfers = _rts;
                return View("Profile");
            }
        }


        [HttpGet]
        public ActionResult AddTransfer(CustomerVM inCVM)
        {
            ViewBag.Customer = inCVM.Customer;
            return View("CreateTransfer");
        }

        [HttpPost]
        public ActionResult CreatTransfer(TransferVM inTVM)
        {
            PWServiceClient pwc = new PWServiceClient();
            
            inTVM.Transfer.WhenDT = DateTime.Now;
            pwc.CreateTransfer(inTVM.Transfer);

            Customer _cust = pwc.Find(inTVM.Transfer.Client);
            List<Transfer> _rts = pwc.FindCustTransfers(_cust.Email);
            ViewBag.Customer = _cust;
            ViewBag.Transfers = _rts;
            return View("Profile");

        }

    }
}

PWWServ_Client/Views/Customer/Create.cshtml
@{
    Layout = null;
}

@model PWWServ_Client.ViewModels.CustomerVM

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm("Create", "Customer"))
    {
        <table cellpadding="1" cellspasing="1" border="0">
            <tr>
                <td>@Html.LabelFor(model => model.Customer.Email)</td>
                <td>@Html.TextBoxFor(model => model.Customer.Email)</td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.Customer.FirstName)</td>
                <td>@Html.TextBoxFor(model => model.Customer.FirstName)</td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.Customer.SecondName)</td>
                <td>@Html.TextBoxFor(model => model.Customer.SecondName)</td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.Customer.PassHesh)</td>
                <td>@Html.TextBoxFor(model => model.Customer.PassHesh)</td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td><input type="submit" value="Save"></td>
            </tr>
            
        </table>    
    }
</body>
</html>

PWWServ_Client/Views/Customer/CreateCopyTransfer.cshtml
@{
    Layout = null;
}

@model PWWServ_Client.ViewModels.TransferVM

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CreateCopyTransfer</title>
</head>
<body>
    <div>
        <p>Under constaction...</p>
        <br />
        <a href="@Url.Action("Index")">Home.</a>
    </div>
</body>
</html>

PWWServ_Client/Views/Customer/CreateTransfer.cshtml
@{
    Layout = null;
}

@model PWWServ_Client.ViewModels.TransferVM

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CreateTransfer</title>
</head>
<body>
    @using (Html.BeginForm("CreatTransfer", "Customer"))
    {
        
        <table cellpadding="1" cellspasing="1" border="0">
            <tr>
                <td>@Html.LabelFor(model => model.Transfer.Client)</td>
                <td>@Html.TextBoxFor(model => model.Transfer.Client)</td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.Transfer.Summa)</td>
                <td>@Html.TextBoxFor(model => model.Transfer.Summa)</td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.Transfer.Amount)</td>
                <td>@Html.TextBoxFor(model => model.Transfer.Amount)</td>
            </tr>
            <tr>
                <td>@Html.LabelFor(model => model.Transfer.Notes)</td>
                <td>@Html.TextBoxFor(model => model.Transfer.Notes)</td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td><input type="submit" value="Add transfer"></td>
            </tr>
            
        </table>    
    }
</body>
</html>

PWWServ_Client/Views/Customer/ErrorLogin.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ErrorLogin</title>
</head>
<body>
    <div>
        <h3>Customer with such e-mail and password not found!</h3>
        <br />
        <a href="@Url.Action("Login", "Customer")">Try agen...</a>
        <br />
        <a href="@Url.Action("Index")">...or go home.</a>
    </div>
</body>
</html>

PWWServ_Client/Views/Customer/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <br />
    <br />
    <a href="@Url.Action("Login", "Customer")">Login</a>
    <br />
    <a href="@Url.Action("Create", "Customer")">Register</a>
</body>
</html>

PWWServ_Client/Views/Customer/Login.cshtml
@{
    Layout = null;
}

@model PWWServ_Client.ViewModels.CustomerVM

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
</head>
<body>
    @using (Html.BeginForm("Login", "Customer"))
    {
        <table cellpadding="1" cellspasing="1" border="0">
            <tr>
                <td>@Html.LabelFor(model => model.Customer.Email)</td>
                <td>@Html.TextBoxFor(model => model.Customer.Email)</td>
            <tr>
            </tr>
                <td>@Html.LabelFor(model => model.Customer.PassHesh)</td>
                <td>@Html.TextBoxFor(model => model.Customer.PassHesh)</td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td><input type="submit" value="Login"></td>
            </tr>
            <tr>
                <td><a href="@Url.Action("Create", "Customer")">Register</a></td>
                <td>&nbsp;</td>
            </tr>
        </table>    
    }
</body>
</html>

PWWServ_Client/Views/Customer/Profile.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Profile</title>
</head>
<body>
    <br /><br />
    <table cellpadding="1" cellspasing="1" border="1">
        <tr>
            <th>E-Mail</th>
            <td>@ViewBag.Customer.Email</td>
        </tr>
        <tr>
            <th>First Name</th>
            <td>@ViewBag.Customer.FirstName</td>
        </tr>
        <tr>
            <th>Second Name</th>
            <td>@ViewBag.Customer.SecondName</td>
        </tr>
    </table>
    <br />
    <table cellpadding="1" cellspasing="1" border="1">
        <tr>
            <th>Id</th>
            <th>When</th>
            <th>Summa</th>
            <th>Amount</th>
            <th>Notes</th>
            <th>Source</th>
            <th>&nbsp</th>
        </tr>
        @if (ViewBag.Transfers != null)
        {
            foreach (var _t in ViewBag.Transfers)
            {
                <tr>
                    <td>@_t.Id</td>
                    <td>@_t.WhenDT</td>
                    <td>@_t.Summa</td>
                    <td>@_t.Amount</td>
                    <td>@_t.Notes</td>
                    <td>@_t.Source</td>
                    <td>&nbsp</td>
                </tr>
            }
            <tr>
                <td colspan="7" align="Center"><a href="@Url.Action("AddTransfer", "Customer")">Add transfer</a></td>
            </tr>
            
        }
        else
        {
            <tr>
                <td colspan="6">No transfers</td>
                <td><a href="@Url.Action("AddTransfer", "Customer")">Add</a></td>
            </tr>
        }
    </table>
    <br /><br />
    <a href="@Url.Action("Index")">Home</a>
</body>
</html>